{{- $hasBearerToken := and .Values.vm.bearerToken (not (kindIs "map" .Values.vm.bearerToken)) }}
{{- $hasCloudAPIKey := gt (len .Values.vm.cloudAPIKey) 0 }}
{{- $hasHeaders := gt (len .Values.vm.headers) 0 }}
{{- if or $hasBearerToken $hasCloudAPIKey $hasHeaders }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-victoriametrics.fullname" . }}
  labels: {{ include "mcp-victoriametrics.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $hasCloudAPIKey }}
  cloud-api-key: {{ .Values.vm.cloudAPIKey | b64enc | quote }}
  {{- end }}
  {{- if $hasBearerToken }}
  bearer-token: {{ .Values.vm.bearerToken | b64enc | quote }}
  {{- end }}
  {{- if $hasHeaders }}
  headers: {{ join "," .Values.vm.headers | b64enc | quote }}
  {{- end }}
{{- end }}
